### ISSUE TITLE
[Discuss] Define errors

### ISSUE THREAD

**Issue by gbonnema** [Nicoretti/xxd-rs#12]
As discussed in #11 we need to refactor out our errors. Looking at these I became aware you were using a crate (`failure`) in which the docs specify:
```
As a general rule, library authors should create their own error types 
and implement Fail for them, whereas application authors should 
primarily deal with the Error type.
```

So, I guess the assignment is to define our own errors in the xxd library and implement the trait `fail` for them.. From the code in bin we should use `failure::Error`. 

If I understand the intention right, this means the application code should never worry about the specifics of the underlying errors, until reporting on a specific error.

This issue could serve as a reminder to do this when the time for it arises.

**Comment by Nicoretti** [comment]
@gbonnema thx for creating the discussion issue, I'll need to revisit the code and the failure create in order to give better feedback on this issue. Hopefully I'll find some time for that next week.

**Comment by gbonnema** [comment]
It's fine, no hurry, it's just a reminder to improve error handling .... some day :-)
