### ISSUE TITLE
`dump_iterator` always starts with address 0

### ISSUE THREAD

**Issue by nkaretnikov** [Nicoretti/xxd-rs#13]
See https://github.com/Nicoretti/xxd-rs/blob/master/src/xxd/dump.rs#L226

To fix: read the address from `output_settings` instead. Note: when printing the address, the `output_fmt` needs to be taken into account (i.e., `Hex` if it's used, otherwise`HexUpperCase`).

Probably related: https://github.com/Nicoretti/xxd-rs/issues/8

**Comment by Nicoretti** [comment]
@nkaretnikov thx for looking into this issue, the referenced PR should fix the issue.

best
Nico
