### ISSUE TITLE
Finish github actions release builds

### ISSUE THREAD

**Issue by martinlindhe** [Nicoretti/xxd-rs#19]
github actions config was added in https://github.com/Nicoretti/xxd-rs/commit/51dd293842e979e1cd20f2d20d9a5f08f4f38e57

Hopefully this is enough to produce release binaries for the next tagged release.
If so, please cut a new release.

If not, then here is a rust binary crate I set up that does produce release binaries from git tags:

https://github.com/martinlindhe/eqformat_pfs/blob/master/.github/workflows/release.yaml

Background: Developing on multiple os:es, I miss xxd on Windows.
This software could fill the gap but in order for easy installation with scoop or chocolatey, release binaries should be available at least for the windows platform.

**Comment by Nicoretti** [comment]
Hi @martinlindhe,

looks like it just works fine with the latest actions (https://github.com/Nicoretti/xxd-rs/releases/tag/xxd-rs-0.2.7).

best
Nico
